//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DX_tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Самосознание – способность осознавать свои эмоции, мотивы и потребности. ")]
        public string Sam {
            get {
                return ((string)(this["Sam"]));
            }
            set {
                this["Sam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Низкий (0-2 балла) уровень самосознания означает несформированную способность осо" +
            "знания своих эмоций, мотивов и потребностей, осложняющую работу, связанную с упр" +
            "авлением, общением, обслуживанием, воспитанием, обучением.")]
        public string Sam_low {
            get {
                return ((string)(this["Sam_low"]));
            }
            set {
                this["Sam_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Средний (3-4) уровень самосознания означает недостаточно сформированную способнос" +
            "ть осознания своих эмоций, мотивов и потребностей, затрудняющую профессиональное" +
            " и личностное развития.")]
        public string Sam_med {
            get {
                return ((string)(this["Sam_med"]));
            }
            set {
                this["Sam_med"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Высокий (5-6) уровень самосознания означает способность осознания своих эмоций, м" +
            "отивов и потребностей, дающую возможность прогнозировать успешность в профессиях" +
            ", связанных с управлением, общением, обслуживанием, воспитанием, обучением.")]
        public string Sam_high {
            get {
                return ((string)(this["Sam_high"]));
            }
            set {
                this["Sam_high"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Эмпатия – умение ставить себя на место другого, учитывать в процессе принятия реш" +
            "ений чувства и эмоции других людей. ")]
        public string Empatia {
            get {
                return ((string)(this["Empatia"]));
            }
            set {
                this["Empatia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Низкий (0-2) уровень эмпатии свидетельствует о слабой способности понимать чувств" +
            "а, мотивы и потребности других людей и может препятствовать эффективному выполне" +
            "нию работы, связанной с управлением, общением, обслуживанием, воспитанием, обуче" +
            "нием.")]
        public string Em_low {
            get {
                return ((string)(this["Em_low"]));
            }
            set {
                this["Em_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Средний (3-4) уровень эмпатии может осложнять профессиональную деятельность в сфе" +
            "рах, связанных с управлением, общением, обслуживанием, воспитанием, обучением.")]
        public string Em_med {
            get {
                return ((string)(this["Em_med"]));
            }
            set {
                this["Em_med"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Высокий (5-6) уровень эмпатии является профессионально важным качеством для профе" +
            "ссий, связанных с управлением, общением, обслуживанием, воспитанием, обучением.")]
        public string Em_high {
            get {
                return ((string)(this["Em_high"]));
            }
            set {
                this["Em_high"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Саморегуляция – способность управлять своими эмоциями. ")]
        public string Reg {
            get {
                return ((string)(this["Reg"]));
            }
            set {
                this["Reg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Низкий (0-2 балла) уровень самоконтроля может проявляться в виде эмоциональной не" +
            "устойчивости, тревожности, утомляемости, осложняя профессиональную деятельность," +
            " связанную с управлением, общением, обслуживанием, воспитанием, обучением.")]
        public string Reg_low {
            get {
                return ((string)(this["Reg_low"]));
            }
            set {
                this["Reg_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Средний (3-4) уровень самоконтроля означает недостаточную способность управлять с" +
            "воими эмоциями, затрудняющую профессиональную и социальную адаптацию человека.")]
        public string Reg_med {
            get {
                return ((string)(this["Reg_med"]));
            }
            set {
                this["Reg_med"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Высокий (5-6) уровень самоконтроля позволяет людям контролировать свое эмоциональ" +
            "ное состояние, что является профессионально важным качеством в профессиях, связа" +
            "нных с управлением, общением, обслуживанием, воспитанием, обучением.")]
        public string Reg_high {
            get {
                return ((string)(this["Reg_high"]));
            }
            set {
                this["Reg_high"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Навыки взаимодействия – доброжелательный интерес к людям, готовность к сотрудниче" +
            "ству.")]
        public string Skills {
            get {
                return ((string)(this["Skills"]));
            }
            set {
                this["Skills"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Низкий (0-2) уровень затрудняет работу, связанную с управлением, общением, обслуж" +
            "иванием, воспитанием, обучением.")]
        public string Skills_low {
            get {
                return ((string)(this["Skills_low"]));
            }
            set {
                this["Skills_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Средний (3-4) уровень может осложнять деятельность, связанную с управлением, обще" +
            "нием, обслуживанием, воспитанием, обучением.")]
        public string Skills_med {
            get {
                return ((string)(this["Skills_med"]));
            }
            set {
                this["Skills_med"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Высокий (5-6) уровень способствует эффективному взаимодействию с другими людьми и" +
            " является профессионально важным качеством для профессий, связанных с управление" +
            "м, общением, обслуживанием, воспитанием, обучением.")]
        public string Skills_high {
            get {
                return ((string)(this["Skills_high"]));
            }
            set {
                this["Skills_high"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Самомотивация – способность ставить перед собой цели и достигать их.")]
        public string Motivation {
            get {
                return ((string)(this["Motivation"]));
            }
            set {
                this["Motivation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Низкий (0-2) уровень самомотивации может негативно влиять на профессиональную усп" +
            "ешность в различных сферах.")]
        public string Motivation_low {
            get {
                return ((string)(this["Motivation_low"]));
            }
            set {
                this["Motivation_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Средний (3-4) уровень самомотивации может осложнять профессиональную деятельность" +
            ".")]
        public string Motivation_med {
            get {
                return ((string)(this["Motivation_med"]));
            }
            set {
                this["Motivation_med"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Высокий (5-6) уровень самомотивации способствует достижению поставленных целей и " +
            "позволяет прогнозировать профессиональную успешность в различных сферах.")]
        public string Motivation_high {
            get {
                return ((string)(this["Motivation_high"]));
            }
            set {
                this["Motivation_high"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string temp_str {
            get {
                return ((string)(this["temp_str"]));
            }
            set {
                this["temp_str"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("физика и математика  ")]
        public string COUNT_FIZ {
            get {
                return ((string)(this["COUNT_FIZ"]));
            }
            set {
                this["COUNT_FIZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("химия и биология  ")]
        public string COUNT_BIO {
            get {
                return ((string)(this["COUNT_BIO"]));
            }
            set {
                this["COUNT_BIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("радиотехника и электроника  ")]
        public string COUNT_ELEC {
            get {
                return ((string)(this["COUNT_ELEC"]));
            }
            set {
                this["COUNT_ELEC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("механика и конструирование  ")]
        public string COUNT_MECH {
            get {
                return ((string)(this["COUNT_MECH"]));
            }
            set {
                this["COUNT_MECH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("география и геология, биология ")]
        public string COUNT_GEO {
            get {
                return ((string)(this["COUNT_GEO"]));
            }
            set {
                this["COUNT_GEO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("литература и искусство  ")]
        public string COUNT_LIT {
            get {
                return ((string)(this["COUNT_LIT"]));
            }
            set {
                this["COUNT_LIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("история и политика  ")]
        public string COUNT_HIS {
            get {
                return ((string)(this["COUNT_HIS"]));
            }
            set {
                this["COUNT_HIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("педагогика и психология ")]
        public string COUNT_MED {
            get {
                return ((string)(this["COUNT_MED"]));
            }
            set {
                this["COUNT_MED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("иностранные языки  ")]
        public string COUNT_LANG {
            get {
                return ((string)(this["COUNT_LANG"]));
            }
            set {
                this["COUNT_LANG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("спорт и военное дело  ")]
        public string COUNT_SPORT {
            get {
                return ((string)(this["COUNT_SPORT"]));
            }
            set {
                this["COUNT_SPORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Пять  баллов говорят о ярко выраженном интересе к предмету или виду деятельности." +
            " Это – необходимое, но недостаточное условие правильного выбора профессии. Друго" +
            "е важное условие – способности, или профессионально важные качества. \r\n\r\n")]
        public string Profile_info {
            get {
                return ((string)(this["Profile_info"]));
            }
            set {
                this["Profile_info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Если сумма баллов ни в одной колонке не превышает трех баллов, значит, профессио" +
            "нальные интересы слабо выражены. ")]
        public string Profile_info2 {
            get {
                return ((string)(this["Profile_info2"]));
            }
            set {
                this["Profile_info2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"0—6 — низкий уровень тревожности. Вас не слишком беспокоят ваши отношения с людьми и ваши успехи или неуспехи в школе. Возможно, все в вашей жизни складывается так хорошо, что вас даже не беспокоят эти вопросы. Или природа наградила вас темпераментом, который позволяет невозмутимо воспринимать укусы и удары судьбы. Вам можно позавидовать. Главное, чтобы ваша эмоциональная броня не мешала вам общаться с людьми. Третий вариант — проблемы есть, но вы делаете вид, что их нет. ")]
        public string Trevog_low1 {
            get {
                return ((string)(this["Trevog_low1"]));
            }
            set {
                this["Trevog_low1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"7—13 — средний уровень тревожности. Умеренный уровень тревожности оказывает на человека стимулирующее действие. Однако вам следует учитывать, что ваше внутренне состояние неустойчиво и зависит от влияния внешних факторов – успех или неуспеха в делах, отношений с близкими людьми, здоровья. ")]
        public string Trevog_med {
            get {
                return ((string)(this["Trevog_med"]));
            }
            set {
                this["Trevog_med"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"14—20 — высокий уровень тревожности. Вероятно, вы часто испытываете нервное перенапряжение. Обратите внимание на режим дня, займитесь спортом, пересмотрите свои привычки. Определите, что для вас сейчас самое главное, и на время отложите второстепенные дела. Не сравнивайте себя с другими! Возможно, у вас более тонкая и чувствительная нервная система, чем у других людей. Учитывайте это при планировании своей работы. Не стремитесь к общению с большим числом людей. 
")]
        public string Trevog_high1 {
            get {
                return ((string)(this["Trevog_high1"]));
            }
            set {
                this["Trevog_high1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Люди с высокой тревожностью беспричинно волнуются по поводу предстоящих событий. " +
            "Волнение и неуверенность мешают им достичь успеха. Людям с высокой тревожностью " +
            "полезно научиться управлять своим психическим состоянием. ")]
        public string Trevog_high2 {
            get {
                return ((string)(this["Trevog_high2"]));
            }
            set {
                this["Trevog_high2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Люди с низкой тревожностью в экстремальных ситуациях выглядят не лучшим образом. Слишком спокойные и самоуверенные, они оказываются в нужный момент  неподготовленными. Обычно у них низкая мотивация достижений. Им также необходимо учиться управлять своим психическим состоянием, чтобы в ситуациях экзамена или соревнований, которые для всех являются стрессовыми, показать все, на что способны.")]
        public string Trevog_low2 {
            get {
                return ((string)(this["Trevog_low2"]));
            }
            set {
                this["Trevog_low2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string t1 {
            get {
                return ((string)(this["t1"]));
            }
            set {
                this["t1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string t2 {
            get {
                return ((string)(this["t2"]));
            }
            set {
                this["t2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string t3 {
            get {
                return ((string)(this["t3"]));
            }
            set {
                this["t3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string t4 {
            get {
                return ((string)(this["t4"]));
            }
            set {
                this["t4"] = value;
            }
        }
    }
}
